language: python
sudo: false
env:
  global:
    - ARTIFACTS_S3_BUCKET=plone-app-mosaic
    - secure: F9djE/1a4VvCidHCnWeF7qkwsUhVLZELv/ttSC1UamsbCCzIa0shUheF4MfAZBRcwtVVAlrid4VRnuYnxyDciy2jrL/qayLfze2ZKcZTfYKsNIrQzyZ4SUVZRB9ZSA6yUK3v+/GIie95as8MKM/UxRtn2RWw4doWGyKv8XBOL4U=
    - secure: buYYreaObmTNEuVTibj/kIyFnIoHCZdezeA8P0HwGHrTbIAwArBFfhG5PC1grT8MayN3f4sfY80d8sRhRATTPNX1smjjBfyni/Zon8OTpr6mGaGsHOg+HHHqocy3hZPlgg1yYLpUCfKCOc8pnq09lF06JwPxsIXAiV+oRHR446E=
addons:
  # XXX: use an older Firefox ESR as we are stuck with selenium = 2.53.5
  #      https://github.com/SeleniumHQ/selenium/issues/2739#issuecomment-249482533
  firefox: 45.9.0esr
matrix:
  include:
    - python: "2.7"
      env: PLONE_VERSION=5.1.x
    - python: "2.7"
      env: PLONE_VERSION=5.2.x
    - python: "3.6"
      env: PLONE_VERSION=5.2.x
    - python: "3.7"
      env: PLONE_VERSION=5.2.x
      dist: xenial
      sudo: true
cache:
  pip: true
  directories:
    - node_modules
    - components
    - $HOME/buildout-cache
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - mkdir $HOME/.buildout
  - echo "[buildout]" > $HOME/.buildout/default.cfg
  - echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
  - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
  - pip install zc.buildout
  - cp test-$PLONE_VERSION.cfg buildout.cfg
install:
  - nvm install node
  - nvm use node
  - rm -rf $HOME/buildout-cache/eggs/plone.app.locales*
  - buildout -N -t 3 annotate
  - buildout -N -t 3
  - mkdir -p parts/test/_screenshots
  - make install
  - make clean all mode=release
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - firefox -v
script:
# Run code-analysis, except on Python 3.6, which mysteriously fails to find zc.buildout.
  - python --version 2> /dev/stdout | grep 3.6 || bin/code-analysis
  - bin/test $TEST_OPTIONS
  - bin/pybot -v SELENIUM2LIBRARY_RUN_ON_FAILURE:"Capture Page Screenshot" -d parts/test docs
after_script:
  - bin/createcoverage --output-dir=parts/test/coverage
#  - bin/sphinx-build docs html
#  - bundle install
#  - bundle exec travis-artifacts upload --path html
#  - bundle exec travis-artifacts upload --path parts/test
#  - bundle exec travis-artifacts upload --target-path latest --path html
#  - bundle exec travis-artifacts upload --target-path latest --path parts/test
#  - 'echo "Sphinx: http://plone-app-mosaic.s3-website-us-east-1.amazonaws.com/artifacts/${TRAVIS_BUILD_NUMBER}/${TRAVIS_JOB_NUMBER}/"'
#  - 'echo "Robot: http://plone-app-mosaic.s3-website-us-east-1.amazonaws.com/artifacts/${TRAVIS_BUILD_NUMBER}/${TRAVIS_JOB_NUMBER}/report.html"'
after_success:
  - pip install -q coveralls
  - coveralls
notifications:
  irc: irc.freenode.org#plone-testing
#irc:
#  template:
#    - '%{repository}#%{build_number} (%{branch} | %{commit} | %{author}): %{message}'
#    - 'Change: %{compare_url}'
#    - 'Details: %{build_url}'
#    - 'Artifacts: http://plone-app-mosaic.s3-website-us-east-1.amazonaws.com/latest/'
